options:
  should-print-debug-message-to-console: false
  should-punish-suspected-player-address: false
  should-broadcast-message-to-staff: false
  should-broadcast-punishment-removal-to-staff: false
  default-address-punishment-duration: 60
