options:
  consoleShouldPrintDebugMessage: false
  shouldPunishPlayerAddress: false
  shouldBroadcastFrozenPlayerStaffMessage: false
  shouldBroadcastUnFrozenPlayerStaffMessage: false
  defaultPunishPlayerAddressDuration: 60
